services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    expose:
      - 5432:5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data:Z
    networks: ["pgtk_chedule_network"]
volumes:
  database:
networks:
  pgtk_chedule_network: {}
